import random

#Function to display instructions
def instructions():
    print("*************************************Instruction*************************************")
    print("* You have to gueass the 4 digit number which is randomly generated by the computer.")
    print("* Random number lies between 1000 to 9999.")
    print("* Every digit value is different from each other.")
    print("* Number of cows means number of digits which are misplaced in your inputed number according to random number.")
    print("* Number of bulls means number of digits which are correctly placed in your inputed number according to random number.")
    print("* You have 5 tries, but it will increase by adding number of bulls in each input.")

#Function to generate a 4 digit randmon number
def generate_number():

    # Create a list of all the digits from 0 to 9.
    digits = list(range(10))

    # Use the random.sample() function to randomly select a number from the list of digits.
    random_number = random.sample(digits,4)

    if random_number[0] != 0:
        return random_number

#Function to find cows( number of digits which are misplaced in your inputed number )
def check_cows(random_num, ply_num_list):
    cow = 0
    for i in random_num:
        for j in ply_num_list:
            if not(random_num.index(i) == ply_num_list.index(j)) and i == j:
                cow += 1
    return cow

#Function to find bulls( number of digits which are correctly placed in your inputed number )
def check_bulls(random_num, ply_num_list):
    bull = 0
    for i in range(4):
        if random_num[i] == ply_num_list[i]:
            bull += 1
    return bull

#main function
def main(random_number,tries):
    while tries>0:
    
        print("**********To exit the game input -1**********")
        ply_num = int(input('Enter a number: '))

        if ply_num == -1:
            print("Thanks for playing")
            break

        ply_num_list = list(map(int,str(ply_num)))
        if len(ply_num_list)<4 or len(ply_num_list)>4:
            print("**********Inputed number's length is less or greater than 4. Input a 4 digit value**********")

        else:
            cows = check_cows(random_number,ply_num_list)
            bulls = check_bulls(random_number,ply_num_list)

            if random_number == ply_num_list:
                print("\n********** Congratulations! You guessed it! **********\n")
                break
            else:
                print("\n"f"{cows} Cow and {bulls} Bull""\n")
            tries = tries+bulls
            
        tries -= 1

    if tries == 0:
        print(f"You are out of tries. Number is {random_number}")

if __name__ == '__main__':

    instructions()

    tries = 5
    random_number = generate_number()
    main(random_number,tries)

    